apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-state-metrics-resizer-role
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployment"]
    verbs: ["get","update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-metrics-role
rules:
  - apiGroups: [""]
    resources: ["pods","configmaps","secrets","persistentvolumeclaim","persistentvolume","services","endpoints","namespaces","replicationcontrollers","resourcequota","limitrange",]
    verbs: ["list","watch"]
  - apiGroups: ["apps"]
    resources: ["deployments","statefulsets","daemonsets"]
    verbs: ["list","watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-state-metrics-resizer-binding
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-state-metrics-resizer-role
subjects:
  - kind: ServiceAccount
    name: kube
    namespace: monitoring

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-state-metrics-binding
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state-metrics-role
subjects:
  - kind: ServiceAccount
    name: kube
    namespace: monitoring
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube
  namespace: monitoring


