apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-prometheus
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
      - configmaps
      - nodes
      - ingress
    verbs:
      - get
      - watch
      - list
  - nonResourceURLs:
    - /metrics
    verbs:
      - get
    
