apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sm-node-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: node-exporter
  endpoints:
    - interval: 30s
      path: /metrics
      port: node
