apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: monitoring
  labels:
    exporter: kube-state-metrics
spec:
  type: ClusterIP
  selector:
    exporter: kube-state-metrics
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
