apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: monitoring
  labels:
    name: prometheus-server
spec:
  type: ClusterIP
  selector:
    name: prometheus-server
  ports:
    - name: webs
      protocol: TCP
      port: 80
      targetPort: 9090
